server:
  port: 40109

spring:
  datasource:
    url: jdbc:mysql://124.221.138.245:3306/hanjia?serverTimezone=GMT%2B8
    username: hanjia
    password: abc123456
#  redis:
#    database: 1
#    host: 124.221.138.245
#    port: 6379
#    password: abc13735820244